/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author programador
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mAlumnos = new javax.swing.JMenu();
        mFormAlumnos = new javax.swing.JMenuItem();
        mMaterias = new javax.swing.JMenu();
        mFormMaterias = new javax.swing.JMenuItem();
        mCursadas = new javax.swing.JMenu();
        mAlumnosXMateria = new javax.swing.JMenuItem();
        mInsc = new javax.swing.JMenu();
        mFormInsc = new javax.swing.JMenuItem();
        mCargaNotas = new javax.swing.JMenu();
        mManipNotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mArchivo.setText("Archivo");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        jMenuBar1.add(mArchivo);

        mAlumnos.setText("Alumnos");

        mFormAlumnos.setText("Formulario de Alumnos");
        mFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormAlumnosActionPerformed(evt);
            }
        });
        mAlumnos.add(mFormAlumnos);

        jMenuBar1.add(mAlumnos);

        mMaterias.setText("Materias");

        mFormMaterias.setText("Formulario de Materias ");
        mFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormMateriasActionPerformed(evt);
            }
        });
        mMaterias.add(mFormMaterias);

        jMenuBar1.add(mMaterias);

        mCursadas.setText("Consultas");

        mAlumnosXMateria.setText("Alumnos por Materia");
        mAlumnosXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAlumnosXMateriaActionPerformed(evt);
            }
        });
        mCursadas.add(mAlumnosXMateria);

        jMenuBar1.add(mCursadas);

        mInsc.setText("Inscripciones");

        mFormInsc.setText("Formulario de Inscripciones");
        mFormInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFormInscActionPerformed(evt);
            }
        });
        mInsc.add(mFormInsc);

        jMenuBar1.add(mInsc);

        mCargaNotas.setText("Carga Notas");

        mManipNotas.setText("Manipulacion de Notas");
        mManipNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mManipNotasActionPerformed(evt);
            }
        });
        mCargaNotas.add(mManipNotas);

        jMenuBar1.add(mCargaNotas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumnos va=new VistaAlumnos();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_mFormAlumnosActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void mFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaMaterias vm=new VistaMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_mFormMateriasActionPerformed

    private void mFormInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFormInscActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaInscripciones ins=new VistaInscripciones();
        ins.setVisible(true);
        escritorio.add(ins);
        escritorio.moveToFront(ins);
    }//GEN-LAST:event_mFormInscActionPerformed

    private void mManipNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mManipNotasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaCargarNotas va=new VistaCargarNotas();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_mManipNotasActionPerformed

    private void mAlumnosXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAlumnosXMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaAlumnosMaterias vm=new VistaAlumnosMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_mAlumnosXMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAlumnos;
    private javax.swing.JMenuItem mAlumnosXMateria;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mCargaNotas;
    private javax.swing.JMenu mCursadas;
    private javax.swing.JMenuItem mFormAlumnos;
    private javax.swing.JMenuItem mFormInsc;
    private javax.swing.JMenuItem mFormMaterias;
    private javax.swing.JMenu mInsc;
    private javax.swing.JMenuItem mManipNotas;
    private javax.swing.JMenu mMaterias;
    private javax.swing.JMenuItem mSalir;
    // End of variables declaration//GEN-END:variables
}
